name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  pull_request:
    branches: main
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup PHP Action
        uses: shivammathur/setup-php@2.25.5
        with:
          php-version: '8.2'
      - uses: 'ramsey/composer-install@v2'
        name: Install Composer & Dependencies
      - name: Generate php artisan key
        run: |
          composer run post-root-package-install
          php artisan key:generate
      - name: Run PHPUnit tests
        run: |
          php artisan test
          